FROM jupyter/scipy-notebook:lab-3.4.0

# Install additional dependencies
# ...
# e.g.:
#    USER root              # switch to the root user first
#    RUN apt-get update
#    RUN apt-get install gcc graphviz graphviz-dev -y

# Make sure to use the jovyan user
USER jovyan

# Exposed HTTP port
EXPOSE 8888